controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    use_stamped_vel: false

    left_wheel_names: ["rear_left_wheel_joint"]
    right_wheel_names: ["rear_right_wheel_joint"]

    wheel_separation: 0.908
    wheel_radius: 0.09

    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0

    command_interfaces: ["velocity"]
    state_interfaces: ["position", "velocity"]

    enable_odom_tf: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 2.0